// Datos reales del prototipo original (Dashboard GestionComercial SKANDIA CREA 2026.html)
// Extraidos 1:1 de C:/Proyectos-indexar/Libertadora/app.js -- NO son datos de ejemplo.

export const PROSPECTOS_REALES = [
  {
    "empresa": "ROBERTO MUÑETON",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita realizada CREA P PJ. Apertura 1er trimestre",
    "estado": "CERRADO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Gestionar referidos",
    "fecha": "",
    "trimestre": "Q1",
    "tipo": "PJ"
  },
  {
    "empresa": "JUAN C ANGARITA",
    "producto": "CREA AHORRO",
    "gestion": "Cita AHORRO PN. Apertura 1er trimestre $300,000",
    "estado": "CERRADO",
    "monto": 300000,
    "prioridad": "ALTA",
    "accion": "Gestionar referidos",
    "fecha": "",
    "trimestre": "Q1",
    "tipo": "PN"
  },
  {
    "empresa": "IMC DEPOSITO SAS",
    "producto": "ARL COLMENA",
    "gestion": "Cita ARL COLMENA. Apertura 1er trimestre",
    "estado": "CERRADO",
    "monto": 0,
    "prioridad": "ALTA",
    "accion": "Renovación ARL",
    "fecha": "",
    "trimestre": "Q1",
    "tipo": "PJ"
  },
  {
    "empresa": "IMC CARGO INTERNACIONAL SAS",
    "producto": "ARL COLMENA",
    "gestion": "Cita ARL COLMENA. Apertura 1er trimestre",
    "estado": "CERRADO",
    "monto": 0,
    "prioridad": "ALTA",
    "accion": "Renovación ARL",
    "fecha": "",
    "trimestre": "Q1",
    "tipo": "PJ"
  },
  {
    "empresa": "LOGIMAT SAS",
    "producto": "ARL COLMENA",
    "gestion": "Cita ARL COLMENA. Apertura 1er trimestre",
    "estado": "CERRADO",
    "monto": 0,
    "prioridad": "ALTA",
    "accion": "Renovación ARL",
    "fecha": "",
    "trimestre": "Q1",
    "tipo": "PJ"
  },
  {
    "empresa": "LINA GONZALEZ",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA PATRIMONIO PN. Apertura 2do trimestre $505,000",
    "estado": "CERRADO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Gestionar referidos",
    "fecha": "",
    "trimestre": "Q2",
    "tipo": "PN"
  },
  {
    "empresa": "LEONARDO ESPISONDOLA TRAMITES",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cliente cerrado CREA PATRIMONIO mayo. Pendiente historia clínica. Apertura agosto",
    "estado": "CERRADO",
    "monto": 504000,
    "prioridad": "ALTA",
    "accion": "Verificar historia clínica para apertura",
    "fecha": "2026-08-01",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "EVA EVOLUTION",
    "producto": "CREA AHORRO",
    "gestion": "Cita CREA AHORRO. Interesada. Apertura agosto $300,000",
    "estado": "CERRADO",
    "monto": 300000,
    "prioridad": "ALTA",
    "accion": "Gestionar referidos",
    "fecha": "2026-08-01",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "VICTOR QUINTERO",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA PATRIMONIO PN. Interesado. Apertura programada 27/07",
    "estado": "INTERESADO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Confirmar apertura 27/07",
    "fecha": "2026-07-27",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "INVERSIONES ALDEMAR",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita CREA PATRIMONIO PJ. Interesado. Pendiente 2da cita con dueños",
    "estado": "INTERESADO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Programar 2da cita con dueños",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "MAKROINMOBILIARIA / CONSTRUCCIONES",
    "producto": "PORTAFOLIO",
    "gestion": "Cita portafolio completo. Interesado en ARL, seguridad y Skandia. Pendiente vinculación socios",
    "estado": "INTERESADO",
    "monto": 0,
    "prioridad": "ALTA",
    "accion": "Pendiente vinculación socios Skandia",
    "fecha": "2027-01-01",
    "trimestre": "Q4",
    "tipo": "PJ"
  },
  {
    "empresa": "CACHIVACHES",
    "producto": "ARL COLMENA",
    "gestion": "Cita RR.HH. para ARL COLMENA. Interesado para el próximo año. Pendiente 2da cita con dueños",
    "estado": "INTERESADO",
    "monto": 0,
    "prioridad": "ALTA",
    "accion": "2da cita con dueños de la compañía",
    "fecha": "",
    "trimestre": "Q4",
    "tipo": "PJ"
  },
  {
    "empresa": "TEATRO NACIONAL",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita Contabilidad para CREA PATRIMONIO PJ. Pendiente 2da visita con RR.HH.",
    "estado": "INTERESADO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "2da cita con RR.HH.",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "NUBIA FORERO",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA PATRIMONIO + CREA AHORRO. Referidos. Interesada, pendiente agosto",
    "estado": "INTERESADO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Apertura agosto CREA P + CREA AHORRO",
    "fecha": "2026-08-01",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "ERNESTO MOSCOSO",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA PATRIMONIO PN. Interesado. Pendiente para diciembre",
    "estado": "INTERESADO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Programar apertura diciembre",
    "fecha": "2026-12-01",
    "trimestre": "Q4",
    "tipo": "PN"
  },
  {
    "empresa": "ALEXIS VILLEGAS",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA PATRIMONIO PN. Interesado. Pendiente apertura agosto",
    "estado": "INTERESADO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Confirmar apertura agosto",
    "fecha": "2026-08-01",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "HILANDERIAS BOGOTA",
    "producto": "PORTAFOLIO",
    "gestion": "Cita dpto contabilidad. 2da cita con gerencia general pendiente",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Programar 2da cita con gerencia",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "MARIA E SANINT",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA PATRIMONIO. Visita para referidos. En proceso",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Seguimiento y referidos",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "ALICIA SUAREZ",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA PATRIMONIO PN para el hijo. En proceso",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Seguimiento cotización para el hijo",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "INVERSIONES Y LOGISTICA SAS",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Concretar cita para ampliar información CREA PATRIMONIO PJ",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Concretar cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "OPTIFAM OPTICA FAMILIAR",
    "producto": "PORTAFOLIO",
    "gestion": "Concretar cita mayo, oferta portafolio completo",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Agendar cita portafolio completo",
    "fecha": "",
    "trimestre": "Q2",
    "tipo": "PJ"
  },
  {
    "empresa": "BOGOTA REAL ESTATE INMOBILIARIA",
    "producto": "PORTAFOLIO",
    "gestion": "Envío brochure. Pendiente respuesta para agendar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Hacer seguimiento respuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "CONFECCIONES DE CALIDAD EM",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita portafolio libertadora y Skandia. Posible CREA PATRIMONIO PJ junio",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Confirmar apertura junio",
    "fecha": "2026-06-01",
    "trimestre": "Q2",
    "tipo": "PJ"
  },
  {
    "empresa": "GLOBAL JOINING",
    "producto": "PORTAFOLIO",
    "gestion": "No interesado en ningún producto. Llamar más adelante",
    "estado": "NO_INTERESADO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Revisitar en 6 meses",
    "fecha": "",
    "trimestre": "Q4",
    "tipo": "PJ"
  },
  {
    "empresa": "MEDICINA INTEGRAL",
    "producto": "PORTAFOLIO",
    "gestion": "Llamada oferta portafolio integral. Me llama si está interesado",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Esperar llamada del cliente",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "TURISMAURO",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita Teams inicios agosto con Sra Natalia — contabilidad@turismauro.com",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Cita Teams agosto con Sra Natalia",
    "fecha": "2026-08-05",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "MAGNO MOBILIARIO",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita Teams mediados de julio",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Cita Teams mediados julio",
    "fecha": "2026-07-15",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "LUXURY HOME CORTINAS",
    "producto": "PORTAFOLIO",
    "gestion": "Cita portafolio completo. No está interesado",
    "estado": "NO_INTERESADO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Ninguna",
    "fecha": "",
    "trimestre": "Q2",
    "tipo": "PJ"
  },
  {
    "empresa": "IMPRESISTEM",
    "producto": "ARL COLMENA",
    "gestion": "Pendiente cita para ARL y CREA PATRIMONIO PJ socios",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Programar cita ARL + CREA P PJ socios",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "KREO PUBLICIDAD",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita oferta CREA P PJ. Interesado",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Enviar propuesta formal",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "ANTS PARTES",
    "producto": "ARL COLMENA",
    "gestion": "Cita con COLMENA para ARL. No interesados por el momento",
    "estado": "NO_INTERESADO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Revisitar próximo año",
    "fecha": "",
    "trimestre": "Q2",
    "tipo": "PJ"
  },
  {
    "empresa": "NAIMA CUBIDES",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA PATRIMONIO. No interesada por el momento",
    "estado": "NO_INTERESADO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Revisitar en 3 meses",
    "fecha": "",
    "trimestre": "Q2",
    "tipo": "PN"
  },
  {
    "empresa": "GRUPO SERATTA",
    "producto": "PORTAFOLIO",
    "gestion": "Envío correo solicitando cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Hacer seguimiento correo",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "AVIATUR",
    "producto": "PORTAFOLIO",
    "gestion": "Cita RR.HH. oferta servicios como grupo. Concretar cita con encargado de seguros",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Concretar cita con encargado de seguros",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "MARIA DEL PILAR CASTIBLANCO",
    "producto": "CREA AHORRO",
    "gestion": "Cita CREA AHORRO. Sin recursos por el momento",
    "estado": "NO_INTERESADO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Revisitar en 6 meses",
    "fecha": "",
    "trimestre": "Q2",
    "tipo": "PN"
  },
  {
    "empresa": "KIOSKOS INFORMATICOS",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA PATRIMONIO. No interesada",
    "estado": "NO_INTERESADO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Ninguna",
    "fecha": "",
    "trimestre": "Q2",
    "tipo": "PN"
  },
  {
    "empresa": "ANCHETAS GOURMET",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita CREA PATRIMONIO PJ. Interesada",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Enviar propuesta formal y confirmar",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "CORONEL RICARDO ORTIZ",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA P. Por edad Skandia no lo recibe. Buscar alternativa",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Buscar producto alternativo",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "ALCUBO",
    "producto": "PORTAFOLIO",
    "gestion": "Llamar próxima semana para 2da cita agosto",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Confirmar 2da cita agosto",
    "fecha": "2026-08-01",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "MILLA EXTRA",
    "producto": "PORTAFOLIO",
    "gestion": "Llamar para programar cita SÁBADO",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Llamar sábado — programar cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "G4",
    "producto": "PORTAFOLIO",
    "gestion": "Llamar fin de semana para 2da cita. Skandia y ARL. Reunión con contador",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "ALTA",
    "accion": "Llamar fin de semana — reunión contador",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "GRUPO GOOD",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA P PN. No interesado, tienen el mismo producto con BMI",
    "estado": "NO_INTERESADO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Identificar diferenciador vs BMI",
    "fecha": "",
    "trimestre": "Q2",
    "tipo": "PN"
  },
  {
    "empresa": "LATIN PARTS",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita CREA. Pendiente 2da cita con contador para socios PJ",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "2da cita con contador para socios",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "PASAROLLA",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita CREA PATRIMONIO PJ. Interesada",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Enviar propuesta formal",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "ALBA BAUTISTA",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA PATRIMONIO para hijo en el extranjero. Por políticas Skandia no fue posible",
    "estado": "CERRADO_NEG",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Buscar alternativa portafolio",
    "fecha": "",
    "trimestre": "Q2",
    "tipo": "PN"
  },
  {
    "empresa": "INDEPENDIENTE SRA PATRICIA",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA PN. No interesada",
    "estado": "NO_INTERESADO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Ninguna",
    "fecha": "",
    "trimestre": "Q2",
    "tipo": "PN"
  },
  {
    "empresa": "CONCEPTO VISUAL",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Programar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "MARQUETLOGIC",
    "producto": "PORTAFOLIO",
    "gestion": "Reprogramar cita, la Sra la aplazó",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Reprogramar cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "THE DOT STUDIO",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Programar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "KAREN VELANDIA",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita CREA PATRIMONIO PJ. No puede por flujo de caja. Llamar más adelante",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "BAJA",
    "accion": "Revisitar en 3 meses",
    "fecha": "",
    "trimestre": "Q4",
    "tipo": "PJ"
  },
  {
    "empresa": "CENTRAL DE SERVICIOS TURISTICOS",
    "producto": "PORTAFOLIO",
    "gestion": "Concretar cita con Recursos Humanos",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Concretar cita con RR.HH.",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "AGENCIA CREATIVA",
    "producto": "PORTAFOLIO",
    "gestion": "Programar 2da cita con contador",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "2da cita con contador",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "SOMOS UNO",
    "producto": "PORTAFOLIO",
    "gestion": "Programar 2da cita con contador",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "2da cita con contador",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "HI HOP",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Programar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "TERMOPOINT ESTAMPADO",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Programar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "ALPIGRAMA",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita con Sra Cecilia Leal para CREA P PJ. Interesada",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Enviar propuesta a Cecilia Leal",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "ASSISTEX",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita sub-gerente CREA P PJ. Pendiente",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Seguimiento sub-gerente",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "ALKOSTO",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Envío correo ARL. Cita CREA P PN. Interesada",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Confirmar propuesta CREA P PN",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "FALABELLA",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "SODEXO",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "PEOPLE PASS",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "COLSUBSIDIO",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "CAT",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "CORFERIAS",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "DANN CARTON CALI",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "HOTEL RADISSON",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "HOTEL MARRIOTT 114",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "HOTEL FOUR POINTS",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "CLUB EL NOGAL",
    "producto": "PORTAFOLIO",
    "gestion": "Envío correo portafolio completo. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita portafolio",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "HOTEL SPIWAK",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "HOTEL HILTON",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "DANN CARTON BARRANQUILLA",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "BASES Y SOPORTES PARA TV",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "SPECIAL EVENTS",
    "producto": "PORTAFOLIO",
    "gestion": "2da cita pendiente con contador",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Programar 2da cita con contador",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "ALEXANDRA PATRICIA ARANGO",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Envío presentación Skandia. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "BLANDERS",
    "producto": "PORTAFOLIO",
    "gestion": "Envío oferta portafolio completo. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Hacer seguimiento",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "MAGNOPRO SOLUCIONES TECNOLOGICAS",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Programar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "ALLMITE PAINTBALL",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Programar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "E TICKET",
    "producto": "PORTAFOLIO",
    "gestion": "2da cita pendiente con contador",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Programar 2da cita con contador",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "LIGHTHOUSE AUDIOVISUAL DESIGN",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Envío presentación CREA P PJ. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita CREA P PJ",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "SOLO STANDS",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Envío presentación CREA P PJ. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita CREA P PJ",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "EXPOSOLAR",
    "producto": "PORTAFOLIO",
    "gestion": "Pendiente confirmación cita en Medellín",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita Medellín",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "XTREME KARTS",
    "producto": "PORTAFOLIO",
    "gestion": "Envío oferta portafolio. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Hacer seguimiento",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "TEXTIPROMOS",
    "producto": "PORTAFOLIO",
    "gestion": "Envío oferta portafolio. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Hacer seguimiento",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "MULTISOFT",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Programar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "MELISSA GAMA",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Programar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "MAKUTE",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Programar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "KIOSCO DEL REGALO",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Programar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "DISTRICONFECCIONES (FABIAN Y SRA NATALY)",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA P PN. Están interesados",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Enviar propuesta — están interesados",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "OSSA Y ASOCIADOS",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Programar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "GASTROWINE",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Programar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "ERNESTO MOSCOSO (2DA VISITA NOCTURNA)",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Programar 2da visita en la noche",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Programar 2da visita nocturna",
    "fecha": "",
    "trimestre": "Q4",
    "tipo": "PN"
  },
  {
    "empresa": "ICON AGENCY",
    "producto": "PORTAFOLIO",
    "gestion": "Envío correo brochure portafolio. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Hacer seguimiento brochure",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "HOTEL STELAR SQUARE",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "HOTEL GHL POPTON",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "HOTEL GHL COTA",
    "producto": "ARL COLMENA",
    "gestion": "Envío correo ARL. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Confirmar cita ARL",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "EMPRESA GRAFICA",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita CREA P PJ. Interesado. Reunión con contadora post 20 mayo",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Reunión con contadora post 20/05",
    "fecha": "2026-05-21",
    "trimestre": "Q2",
    "tipo": "PJ"
  },
  {
    "empresa": "EL CORRAL",
    "producto": "PORTAFOLIO",
    "gestion": "Envío de información. Pendiente seguimiento",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Hacer seguimiento",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "DYNAMIC MERCHANDISING",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Envío propuesta CREA P PJ. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Confirmar cita para propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "LA BOLERA",
    "producto": "PORTAFOLIO",
    "gestion": "Envío oferta portafolio. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Hacer seguimiento",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "SERVICIOS INTEGRALES WUECHUA",
    "producto": "PORTAFOLIO",
    "gestion": "Envío oferta portafolio. Pendiente cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Hacer seguimiento",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "GTS",
    "producto": "PORTAFOLIO",
    "gestion": "Programar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Programar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "ACTIVISION",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita CREA P. No interesado",
    "estado": "NO_INTERESADO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Ninguna",
    "fecha": "",
    "trimestre": "Q2",
    "tipo": "PJ"
  },
  {
    "empresa": "NH HOTELES",
    "producto": "PORTAFOLIO",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta ARL + portafolio",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "XUE",
    "producto": "PORTAFOLIO",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "TECKO",
    "producto": "PORTAFOLIO",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "BARAC PUBLICIDAD SAS",
    "producto": "PORTAFOLIO",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "GRUPO GRAN SELLO",
    "producto": "PORTAFOLIO",
    "gestion": "Cita confirmada 4 de mayo",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Cita 4 de mayo confirmada",
    "fecha": "2026-05-04",
    "trimestre": "Q2",
    "tipo": "PJ"
  },
  {
    "empresa": "PUBLIMARKET",
    "producto": "PORTAFOLIO",
    "gestion": "Concretar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Concretar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "MAEL CHOCOLATES",
    "producto": "PORTAFOLIO",
    "gestion": "Concretar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Concretar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "CAFFA",
    "producto": "PORTAFOLIO",
    "gestion": "Concretar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Concretar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "DISTRICT",
    "producto": "PORTAFOLIO",
    "gestion": "Concretar cita",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Concretar primera cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "BASE PROYECTO SEKY",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Enviar propuesta CREA PATRIMONIO (base antigua Patrimonio A)",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "RAUL ENRIQUE AGUILAR SALINAS",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "ANDRADE ESCOBAR DIEGO",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "MARIA DEL PILAR ANGEL JARAMILLO",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "BELTRAN URIBE PILAR DE LOS ANGELES",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "BRAVO ROSERO ALEJANDRO ESTEBAN",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "CALDERON FORERO ALFONSO",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "CALLE ALVAREZ EDGAR ARTURO",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "CALVO CRUZ ALEJANDRO JOSE",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "CASTRO BARRERO YOHAN FERNANDO",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "CASTRO CARVAJAL MARTHA LUCIA",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "CLARA AZUCENA FLOREZ GONZALEZ",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Enviar propuesta",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "CORPORACION SOCIEDAD PSICOANALITICA FROID",
    "producto": "PORTAFOLIO",
    "gestion": "Enviar propuesta portafolio integral",
    "estado": "EN_PROCESO",
    "monto": 0,
    "prioridad": "MEDIA",
    "accion": "Enviar propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "MANUELA RODRIGUEZ",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA P Y AHORRO PN. Interesada",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Confirmar apertura CREA P + AHORRO",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "MARIA PAULA RAMIREZ",
    "producto": "CREA PATRIMONIO PN",
    "gestion": "Cita CREA P PN. Interesada",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "ALTA",
    "accion": "Confirmar apertura",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  },
  {
    "empresa": "MAGNOINMOBILIARIA",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Cita CREA PATRIMONIO PJ",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Seguimiento propuesta",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "TU EVENTO",
    "producto": "CREA PATRIMONIO PJ",
    "gestion": "Pendiente cita CREA PATRIMONIO PJ",
    "estado": "EN_PROCESO",
    "monto": 505000,
    "prioridad": "MEDIA",
    "accion": "Concretar cita",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PJ"
  },
  {
    "empresa": "GLORIA JARAMILLO",
    "producto": "CREA AHORRO",
    "gestion": "Visita CREA AHORRO. No interesada",
    "estado": "NO_INTERESADO",
    "monto": 0,
    "prioridad": "BAJA",
    "accion": "Ninguna",
    "fecha": "",
    "trimestre": "Q3",
    "tipo": "PN"
  }
] as const

export const CITAS_REALES = [
  {
    "cliente": "VICTOR QUINTERO",
    "fecha": "2026-07-27",
    "hora": "10:00",
    "modalidad": "Presencial",
    "producto": "CREA PATRIMONIO PN",
    "estado": "confirmed",
    "notas": "Apertura CREA PATRIMONIO PN — $505,000/mes"
  },
  {
    "cliente": "TURISMAURO — Sra Natalia",
    "fecha": "2026-08-05",
    "hora": "09:00",
    "modalidad": "Microsoft Teams",
    "producto": "PORTAFOLIO",
    "estado": "pending",
    "notas": "contabilidad@turismauro.com — Portafolio completo"
  },
  {
    "cliente": "NUBIA FORERO",
    "fecha": "2026-08-07",
    "hora": "11:00",
    "modalidad": "Presencial",
    "producto": "CREA PATRIMONIO PN",
    "estado": "pending",
    "notas": "Apertura CREA PATRIMONIO + CREA AHORRO"
  },
  {
    "cliente": "MAGNO MOBILIARIO",
    "fecha": "2026-07-28",
    "hora": "14:00",
    "modalidad": "Microsoft Teams",
    "producto": "PORTAFOLIO",
    "estado": "pending",
    "notas": "Presentación portafolio completo"
  }
] as const
